### ISSUE TITLE
Missing 3DS VC Titles

### ISSUE THREAD

**Issue by metaboss** [DanTheMan827/nus-info#1]
It looks like 3DS virtual console titles are missing.

Examples
The Legend of Zelda the Minish Cap - GBA - titleID 0004000000076d00
Bionic Commando Elite Forces - GBC - titleID 000400000011a800

It'd be awesome if that data were available. It's hard to find good info to relate titleid/serial to virtual console platform (game gear, gb, gbc, nes, snes, etc).

**Comment by DanTheMan827** [comment]
Hmm... the info is on the CDN but it doesn't appear to be in the game list for some reason...

https://samurai.ctr.shop.nintendo.net/samurai/ws/US/title/50010000008222/?shop_id=2
https://samurai.ctr.shop.nintendo.net/samurai/ws/US/title/50010000029275/?shop_id=2

I'll see if I can figure that out...

**Comment by DanTheMan827** [comment]
Sorry that it took so long, the rest of the eShop info should now be in the dataset.
