### ISSUE TITLE
Missing new games

### ISSUE THREAD

**Issue by pong106** [DanTheMan827/nus-info#2]
From my comparison from. 
https://samurai.wup.shop.nintendo.net/samurai/ws/US/titles?limit=9999999
with
complete-us.json

Example of missing game are Miitopia and Ever Oasis.

Thanks for the effort.

**Comment by metaboss** [comment]
Runbow, Samus Returns, etc are also missing

**Comment by DanTheMan827** [comment]
Turns out that the automated process was running out of memory and crashing... everything should be there now.
